hydra:
  job:
    name: ""

# FIXED
is_two_models: False
plm_names: ["roberta-base"]

# Can change
num_passes: 4

add_noise_test: True

do_train: False
do_test: True

overwrite_parent_dir: outputs/2025-08-01/11-12-20_newsemp_cross-prob_lambdas-[1, 9.110462266012783, 5.5635098435909764]_tune-False_single-model_4-passes-label-noise-0.1
