hydra:
  job:
    name: "" # doesn't matter as we save it in the parent dir

approach: cross-basic
is_two_models: False
plm_names: ["roberta-base"]

do_train: False
do_test: True

overwrite_parent_dir: 
