hydra:
  job:
    name: "single-model_${expt.num_passes}-passes"

# FIXED
is_two_models: False
plm_names: ["roberta-base"]

# Can change
num_passes: 4

# [nll, penalty, alignment]
# main_data: newsemp
# lambdas: [1, 17.3, 0.3]

main_data: empstories
lambdas: [1, 32.8, 9.6]

error_decay_factor: 1.5

do_tune: False
do_augment: True

# for resuming experiments
overwrite_parent_dir: null
