hydra:
  job:
    name: "single-model_${expt.num_passes}-passes_modernbert"

# FIXED
is_two_models: False
plm_names: ["microsoft/deberta-v3-base"]
lr: 3.0e-5
wd: 0.01

# Can change
num_passes: 4

# tuned
lambdas: [1, 23.5, 35.5]

error_decay_factor: 1.5

do_tune: False
do_augment: True

# for resuming experiments
overwrite_parent_dir: null
