hydra:
  job:
    name: "single-model_${expt.num_passes}-passes_deberta"

# FIXED
is_two_models: False
plm_names: ["microsoft/deberta-v3-base"]
lr: 3.0e-5
wd: 0.01

# Can change
num_passes: 4

# tuned - newsemp
# main_data: newsemp
# lambdas: [1, 37.6, 19.5]

# tuned - empstories
main_data: empstories
lambdas: [1, 12.9, 13.1]

error_decay_factor: 1.0

do_tune: False
do_augment: True

# for resuming experiments
overwrite_parent_dir: null
