hydra:
  job:
    name: "baseline"

approach: cross-basic
is_two_models: False
plm_names: ["roberta-base"]

lambdas: [null, null, 0]
# [NA, NA, alignment]

num_passes: 1

#### Resume training
overwrite_parent_dir: null
