hydra:
  job:
    name: "single-model_${expt.num_passes}-passes_deberta"

# FIXED
is_two_models: False
plm_names: ["microsoft/deberta-v3-base"]
lr: 3.0e-5
wd: 0.01

# Can change
num_passes: 4

lambdas: [null, null, null] # being tuned / set in optuna objective
# [nll, penalty, alignment]

error_decay_factor: null

main_data: empstories

do_tune: True
n_trials: 20

do_train: False # training immediately after tuning with updated parameters is not properly configured
do_test: False

overwrite_parent_dir: null 
