hydra:
  job:
    name: "${expt.num_passes}-passes-ucvme"

is_ucvme: True
plm_names: ["roberta-base", "roberta-base"]

lambdas: [12.108875317622909, null, null, null, null] # only one weight in UCVME
# lambdas: [12.11, null, null, null, null] # only one weight in UCVME

lbl_split: 1
num_passes: 4

main_data: empstories 

do_tune: False
n_trials: 10
do_train: True

overwrite_parent_dir: null 
