hydra:
  job:
    name: "single-model_${expt.num_passes}-passes-best"

# FIXED
is_two_models: False
plm_names: ["roberta-base"]
main_data: empstories

# Can change
num_passes: 4

lambdas: [1, 44.267427035816425, 21.34894435683186]
# [nll, penalty, alignment]

error_decay_factor: 1.0 # didn't tune, but kept fixed

do_tune: False
do_augment: True

overwrite_parent_dir: null

# if testing only
# do_train: False
# do_test: True
# overwrite_parent_dir: outputs/2025-07-31/00-28-34_empstories_cross-prob_lambdas-[1, 44.267427035816425, 21.34894435683186]_tune-False_single-model_4-passes-optuna-best-lambdas-updated-rescaling
